/**
 * Visum app
 * The API for the Visum music web project
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoginResponseDTO } from './loginResponseDTO';


export interface ApiResponseLoginResponseDTO { 
    result?: LoginResponseDTO;
    errorCode?: string;
    message?: object;
    responseCode?: number;
}

