/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Customer { 
    id?: number;
    userName?: string;
    fullName?: string;
    email?: string;
    genderEnum?: Customer.GenderEnumEnum;
    address?: string;
    phone?: string;
    dateOfBirth?: string;
    role?: string;
}
export namespace Customer {
    export type GenderEnumEnum = 'MALE' | 'FEMALE' | 'OTHER';
    export const GenderEnumEnum = {
        Male: 'MALE' as GenderEnumEnum,
        Female: 'FEMALE' as GenderEnumEnum,
        Other: 'OTHER' as GenderEnumEnum
    };
}


