/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderDetail } from './orderDetail';
import { ShippingMethod } from './shippingMethod';
import { Address } from './address';
import { CardPayment } from './cardPayment';
import { Customer } from './customer';


export interface Order { 
    id?: number;
    orderCode?: string;
    customer?: Customer;
    total?: number;
    status?: Order.StatusEnum;
    deliveryDate?: string;
    orderDate?: string;
    shippingMethod?: ShippingMethod;
    cardPayment?: CardPayment;
    paymentMethodEnum?: Order.PaymentMethodEnumEnum;
    address?: Address;
    orderDetails?: Array<OrderDetail>;
}
export namespace Order {
    export type StatusEnum = 'WAITING_PROCESS' | 'WAITING_DELIVERY' | 'SUCCESS' | 'CANCEL';
    export const StatusEnum = {
        WaitingProcess: 'WAITING_PROCESS' as StatusEnum,
        WaitingDelivery: 'WAITING_DELIVERY' as StatusEnum,
        Success: 'SUCCESS' as StatusEnum,
        Cancel: 'CANCEL' as StatusEnum
    };
    export type PaymentMethodEnumEnum = 'ONLINE_PAYING' | 'DELIVERY_PAYING';
    export const PaymentMethodEnumEnum = {
        OnlinePaying: 'ONLINE_PAYING' as PaymentMethodEnumEnum,
        DeliveryPaying: 'DELIVERY_PAYING' as PaymentMethodEnumEnum
    };
}


