/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShippingMethod } from './shippingMethod';
import { Customer } from './customer';


export interface Order { 
    id?: number;
    orderCode?: string;
    customer?: Customer;
    total?: number;
    status?: Order.StatusEnum;
    deliverDate?: string;
    orderDate?: string;
    shippingMethod?: ShippingMethod;
}
export namespace Order {
    export type StatusEnum = 'WAITING_PROCESS' | 'WAITING_DELIVERY' | 'SUCCESS' | 'CANCEL';
    export const StatusEnum = {
        WaitingProcess: 'WAITING_PROCESS' as StatusEnum,
        WaitingDelivery: 'WAITING_DELIVERY' as StatusEnum,
        Success: 'SUCCESS' as StatusEnum,
        Cancel: 'CANCEL' as StatusEnum
    };
}


