/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderRequest { 
    shippingMethodId?: number;
    paymentMethodEnum?: OrderRequest.PaymentMethodEnumEnum;
    cardNumber?: string;
}
export namespace OrderRequest {
    export type PaymentMethodEnumEnum = 'ONLINE_PAYING' | 'DELIVERY_PAYING';
    export const PaymentMethodEnumEnum = {
        OnlinePaying: 'ONLINE_PAYING' as PaymentMethodEnumEnum,
        DeliveryPaying: 'DELIVERY_PAYING' as PaymentMethodEnumEnum
    };
}


