/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';
import { ImageModel } from './imageModel';


export interface Product { 
    id?: number;
    name?: string;
    content?: string;
    actualPrice?: number;
    featureImageName?: string;
    productImages?: Set<ImageModel>;
    category?: Category;
}

