/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


 export interface ProductRequest { 
    name: string;
    productCode: string;
    parameters: string;
    content: string;
    actualPrice: number;
    quantity: number;
    category_id?: number;
    brand_id?: number;
}

