/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SafeUrl } from '@angular/platform-browser';
import { Brand } from './brand';
import { Category } from './category';
import { ImageModel } from './imageModel';


export interface Product { 
    id?: number;
    name?: string;
    productCode?: string;
    parameters?: string;
    content?: string;
    imgUrl: SafeUrl;
    quantity?: number;
    actualPrice?: number;
    featureImageName?: string;
    featureImageByte?: Array<string>;
    productImages?: Set<ImageModel>;
    category?: Category;
    brand?: Brand;
}

