/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubCategory } from './subCategory';
import { ImageModel } from './imageModel';
import { SafeUrl } from '@angular/platform-browser';


export interface Product { 
    id?: number;
    name?: string;
    productCode?: string;
    parameters?: string;
    content?: string;
    quantity?: number;
    actualPrice?: number;
    shortDescription?: string;
    featureImageName?: string;
    featureImageByte?: Array<string>;
    productImages?: Set<ImageModel>;
    subCategory?: SubCategory;
    imgUrl: SafeUrl
}

