/**
 * Visum app
 * The API for the Visum music web project
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SongDTO { 
    id?: string;
    title?: string;
    image?: string;
    thumbnail?: string;
    genre?: object;
    songAuthor?: object;
    duration?: number;
    vip?: boolean;
}

