/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserRequest { 
    userName?: string;
    password?: string;
    fullName?: string;
    email?: string;
    genderEnum?: UserRequest.GenderEnumEnum;
    address?: string;
    phone?: string;
    dateOfBirth?: string;
    salary?: number;
    roles?: Array<string>;
    customer?: boolean;
}
export namespace UserRequest {
    export type GenderEnumEnum = 'MALE' | 'FEMALE' | 'OTHER';
    export const GenderEnumEnum = {
        Male: 'MALE' as GenderEnumEnum,
        Female: 'FEMALE' as GenderEnumEnum,
        Other: 'OTHER' as GenderEnumEnum
    };
}


