export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './bannerController.service';
import { BannerControllerService } from './bannerController.service';
export * from './categoryController.service';
import { CategoryControllerService } from './categoryController.service';
export * from './customerController.service';
import { CustomerControllerService } from './customerController.service';
export * from './productController.service';
import { ProductControllerService } from './productController.service';
export * from './roleController.service';
import { RoleControllerService } from './roleController.service';
export * from './sliderController.service';
import { SliderControllerService } from './sliderController.service';
export * from './subCategoryController.service';
import { SubCategoryControllerService } from './subCategoryController.service';
export * from './testController.service';
import { TestControllerService } from './testController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AuthControllerService, BannerControllerService, CategoryControllerService, CustomerControllerService, ProductControllerService, RoleControllerService, SliderControllerService, SubCategoryControllerService, TestControllerService, UserControllerService];
